apiVersion: v1
kind: Service
metadata:
  name: {{ template "crud.fullname" . }}
  labels:
    app: crud
    component: api
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: api
  selector:
    app: crud
    component: api
    release: {{ .Release.Name }}
