{
 "title": "Otus app montoring",
 "time": { "from": "2020-08-27T09:10:00.000Z", "to": "2020-08-27T10:05:00.000Z" },
 "panels": [
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le,handler)(rate(http_request_duration_seconds_bucket[1m]))))*1000"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le,handler)(rate(http_request_duration_seconds_bucket[1m]))))*1000"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (le,handler)(rate(http_request_duration_seconds_bucket[1m]))))*1000"
    }
   ]
  },
  {
   "title": "Latency max",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, (sum by (le,handler)(rate(http_request_duration_seconds_bucket[1m]))))*1000"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{status=\"5xx\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Ingress Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))*1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))*1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))*1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))*1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Ingress RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_requests[1m]))"
    }
   ]
  },
  {
   "title": "Ingress error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\"}[1m]) OR on() vector(0))"
    }
   ]
  }
 ]
}