apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crud-chart.fullname" . }}
  labels:
    {{- include "crud-chart.labels" . | nindent 4 }}
data:
  DATABASE_HOST: "{{ .Release.Name }}-crud-db"
  DATABASE_PORT: "{{ .Values.postgresql.service.port }}"
  DATABASE_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DATABASE_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"