apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-chart.fullname" . }}
  labels:
    {{- include "crud-chart.labels" . | nindent 4 }}
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "crud-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: crud-pod
      labels:
        {{- include "crud-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: api
          protocol: TCP
        livenessProbe:
          httpGet:
            port: api
            path: {{ .Values.service.liveness.path }}
          initialDelaySeconds: {{ .Values.service.liveness.initialDelay }}
          periodSeconds: {{ .Values.service.liveness.period }}
        readinessProbe:
          httpGet:
            port: api
            path: {{ .Values.service.readiness.path }}
          initialDelaySeconds: {{ .Values.service.readiness.initialDelay }}
          periodSeconds: {{ .Values.service.readiness.period }}
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "crud-chart.fullname" . }}
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "crud-chart.fullname" . }}
                key: DATABASE_PORT
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: {{ include "crud-chart.fullname" . }}
                key: DATABASE_USER
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "crud-chart.fullname" . }}
                key: DATABASE_NAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: postgresql-password