apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-chart.fullname" . }}
  labels:
    {{- include "crud-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: api
    name: api
  selector:
    {{- include "crud-chart.selectorLabels" . | nindent 4 }}
